export enum AlphabetEnum{
  offices,
  taxi,
  general,
  disabled,
  agriculture,
  b,
  j,
  d,
  sin,
  saad,
  t,
  gh,
  l,
  m,
  n,
  v,
  h,
  y,
}

export const AlphabetEnum2LabelMapping: Record<AlphabetEnum, string> = {
  [AlphabetEnum.offices]: "الف",
  [AlphabetEnum.taxi]: "ت",
  [AlphabetEnum.general] : "ع",
  [AlphabetEnum.disabled]: "ژ",
  [AlphabetEnum.agriculture]: "ک",
  [AlphabetEnum.b]: "ب",
  [AlphabetEnum.j]: "ج",
  [AlphabetEnum.d]: "د",
  [AlphabetEnum.sin]: "س",
  [AlphabetEnum.saad]: "ص",
  [AlphabetEnum.t]: "ت",
  [AlphabetEnum.gh]: "ق",
  [AlphabetEnum.l]: "ل",
  [AlphabetEnum.m]: "م",
  [AlphabetEnum.n]: "ن",
  [AlphabetEnum.v]: "و",
  [AlphabetEnum.h]: "ه",
  [AlphabetEnum.y]: "ی",
}
