import {ReportMetricEnum} from "./report-metric.enum";

export enum ReportActivityDimensionEnum {
  User,
  AssignUser,
  Customer,
  Path,
  Step,
  ActivityType,
  DoneState,
  DeferredState,
  CreateHour,
  CreateDay,
  CreateMonth,
  CreateYear,
  DoneDateHour,
  DoneDateDay,
  DoneDateMonth,
  DoneDateYear,
  DueDateHour,
  DueDateDay,
  DueDateMonth,
  DueDateYear,
}

export const ReportActivityDimensionEnum2LabelMapping : Record<ReportActivityDimensionEnum, string> = {
  [ReportActivityDimensionEnum.User]: 'کارشناس',
  [ReportActivityDimensionEnum.AssignUser]: 'کاربر انتساب دهنده',
  [ReportActivityDimensionEnum.Customer]: 'مشتری',
  [ReportActivityDimensionEnum.Path]: 'کاریز',
  [ReportActivityDimensionEnum.Step]: 'گام',
  [ReportActivityDimensionEnum.ActivityType]: 'نوع فعالیت',
  [ReportActivityDimensionEnum.DoneState]: 'وضعیت انجام',
  [ReportActivityDimensionEnum.DeferredState]: 'وضعیت معوق',
  [ReportActivityDimensionEnum.CreateHour]: 'زمان ایجاد(ساعت)',
  [ReportActivityDimensionEnum.CreateDay]: 'زمان ایجاد(روز)',
  [ReportActivityDimensionEnum.CreateMonth]: 'زمان ایجاد(ماه)',
  [ReportActivityDimensionEnum.CreateYear]: 'زمان ایجاد(سال)',
  [ReportActivityDimensionEnum.DoneDateHour]: 'زمان انجام(ساعت)',
  [ReportActivityDimensionEnum.DoneDateDay]: 'زمان انجام(روز)',
  [ReportActivityDimensionEnum.DoneDateMonth]: 'زمان انجام(ماه)',
  [ReportActivityDimensionEnum.DoneDateYear]: 'زمان انجام(سال)',
  [ReportActivityDimensionEnum.DueDateHour]: 'زمان مقرر(ساعت)',
  [ReportActivityDimensionEnum.DueDateDay]: 'زمان مقرر(روز)',
  [ReportActivityDimensionEnum.DueDateMonth]: 'زمان مقرر(ماه)',
  [ReportActivityDimensionEnum.DueDateYear]: 'زمان مقرر(سال)',
}
